### ISSUE TITLE
Visualising Noahs big year

### ISSUE THREAD

**Issue by mzorgdrager** [mstrimas/mstrimas.github.io#1]
Hello Matt, 

I am blown away by your data visualisation on Noah's big year. Great job!
I am actually a birdwatcher myself and I am eager to learn more about data visualisation. I am completely new to this subject and was wondering where to begin.
I read you use open source program R.
Do you also use D3 in JavaScript? And is any HTML and/or CSS knowledge required for your data visualisation?
Do you have any other tips how to start learning to become a data scientist?

Thanks a lot in advance,
Maarten Zorgdrager (the Netherlands)

**Comment by mstrimas** [comment]
Hi Maarten,

Thanks! I don't use d3, although I'd like to learn it, and the visualization doesn't require javascript, html, or css. It's all done in R using the packages `ggplot2` for visualization and `dplyr` for data manipulation. If you don't already have them, install [R](https://www.r-project.org/) and [Rstudio](https://www.rstudio.com/), then look though some tutorials, for example:

Intro to R and RStudio:
http://stat545-ubc.github.io/block002_hello-r-workspace-wd-project.html

`ggplot`
http://stcorp.nl/R_course/tutorial_ggplot2.html
https://github.com/jennybc/ggplot2-tutorial
http://www.cookbook-r.com/Graphs/

`dplyr`
http://stat545-ubc.github.io/block009_dplyr-intro.html

Good luck!

M

**Comment by mzorgdrager** [comment]
Thanks a lot! 
I have your R code on Noahs big year working on my pc, now I will look further into the ggplot2 and dplyr packages.
By the way, do you know that a Dutch birder is doing a big year at the moment?
His statistics can be seen here: http://world.observation.org/arjan.php

Best regards,
Maarten

**Comment by mstrimas** [comment]
Yes, I have seen that. Very interesting! I think at some point I'll do a post comparing his big year to Noah's.
